### ISSUE TITLE
DiscordMfaToken

### ISSUE THREAD

**Issue by The13thTimelord** [Kaufi-Jonas/Discord-Rich-Presence-for-TIDAL#5]
The Header of "Authorization" doesn't exist anymore and if you refresh on the page it automatically signs you off. So album artwork isn't possible anymore.

**Comment by jonas-kaufmann** [comment]
I just checked and it is still working. I am also signed off in the browser, however, the token keeps working.

Instead of refreshing, I now just clicked something, e.g., the application I created inside Discord's developer portal. Does that work for you?

**Comment by The13thTimelord** [comment]
Hmmm Interesting yeah it does. If DevTools is open it seems to sign you out. Strangly though I am still not getting album artwork
![image](https://user-images.githubusercontent.com/3193292/155013198-6c29051f-3368-4afc-b532-e969c542d37c.png)


EDIT: Working now, Thanks for the help!

**Comment by jonas-kaufmann** [comment]
I am going to update the README, thank you for reporting this. Regarding artwork, it takes ~15 min for it to become available after uploading.
