### ISSUE TITLE
No idea what happened there

### ISSUE THREAD

**Issue by 1nikolas** [Kaufi-Jonas/Discord-Rich-Presence-for-TIDAL#6]
Did it try to add the same cover on discord again?
It's this album https://tidal.com/browse/album/209333039

edit: this cover is not on my assets

I was listening to this https://tidal.com/browse/track/29862946 and normal edition's cover is already on my assets. But it tried to load the deluxe one

![image](https://user-images.githubusercontent.com/30593419/163671595-8b955ba0-32d0-49d5-a447-ce556e64c4d2.png)

**Comment by jonas-kaufmann** [comment]
Hi,
thank you for reporting this bug. I fixed it and published a new release (1.3.3).
